# Generated by Django 4.1.7 on 2024-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='user_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
