# Generated by Django 4.1.7 on 2024-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='user_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
