# Generated by Django 4.1.7 on 2025-04-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tutorprofile_average_rating_twofactorcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoranalyticsview',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
        ),

    ]
