# Generated by Django 4.1.7 on 2025-04-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tutoranalyticsview_view_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterFirstName', models.CharField(max_length=100)),
                ('requesterLastName', models.CharField(max_length=100)),
                ('requesterEmail', models.EmailField(max_length=254)),
                ('requesterDescription', models.TextField()),
                ('tutorID', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

    ]
