# Generated by Django 4.1.7 on 2025-05-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tutorprofile_average_rating_tutorprofile_gender_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tutorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
